q = input('Digite algo: ')
print('O tipo primitivo desse valor é: \033[32m{}'.format(type(q)))
print('É um número? {}'.format(q.isnumeric()))
print('É alfabético? {}'.format(q.isalpha()))
print('É alfanumérico? {}'.format(q.isalnum()))
print('Só tem espaços? {}'.format(q.isspace()))
print('Está em minúsculas? {}'.format(q.islower()))
print('Está em maiúsculas? {}'.format((q.isupper())))
print('Está capitalizada? {}'.format(q.istitle()))